[package]
name = "liblovely"
version = "0.1.0"
edition = "2021"

[lib]
name = "lovely"
crate-type = ["staticlib"]

[dependencies]
lovely-core = { version ="0.9.0", path = "../lovely-core" }

once_cell = "1.19.0"
ctor = "0.2.7"
